name: Main Workflow

on:
  push:
  pull_request:
    branches: [master]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.10.0
      - name: Intall
        run: yarn install --frozen-lockfile
      - name: Check format
        run: yarn format:check
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
